homeassistant:
  customize: !include_dir_named include/customizations/

frontend:
  themes: !include_dir_merge_named include/themes/

cloud:

config:

http: !include include/http.yaml

updater:

discovery:

history:

logbook:

system_health:

sun:

mobile_app:

# Replace built-in SQLite database with mariadb
recorder: !include include/recorder.yaml

# Add InfluxDB as a second database for integration with Grafana
influxdb: !include include/influxdb.yaml

alert: !include_dir_named include/alerts/

automation: !include_dir_merge_list include/automations/

binary_sensor: !include_dir_list include/binary_sensors/

device_tracker: !include_dir_list include/device_trackers/

group: !include_dir_named include/groups/

media_player: !include_dir_list include/media_players/

notify: !include include/notify.yaml

remote: !include_dir_list include/remotes/

script: !include_dir_named include/scripts/

sensor: !include_dir_list include/sensors/

spotify: !include include/spotify.yaml

switch:
  - platform: template
    switches: !include_dir_named include/switches/

utility_meter: !include_dir_named include/utility_meters/

zone: !include_dir_list include/zones/
