homeassistant:
  customize: !include_dir_named include/customizations/

frontend:
  themes: !include_dir_merge_named themes/

cloud:

config:

http: !include include/http.yaml

discovery:

history:

logbook:

system_health:

sun:

mobile_app:

energy:

# Helpers
input_boolean:
input_text:
input_number:
input_datetime:
input_select:
input_button:
counter:
timer:
schedule:

# Replace built-in SQLite database with mariadb
recorder: !include include/recorder.yaml

# Add InfluxDB as a second database for integration with Grafana
influxdb: !include include/influxdb.yaml

alert: !include_dir_merge_named include/alerts/

automation manual: !include_dir_merge_list include/automations/
automation ui: !include automations.yaml

binary_sensor: !include_dir_list include/binary_sensors/

device_tracker: !include_dir_list include/device_trackers/

fan: !include include/fans.yaml

group: !include_dir_named include/groups/

home_connect_alt: !include include/homeconnect.yaml

notify: !include include/notify.yaml

remote: !include_dir_list include/remotes/

scene: !include scenes.yaml

script: !include_dir_named include/scripts/

sensor: !include_dir_list include/sensors/

zone: !include_dir_list include/zones/