# Notify when everyone leaves the home, and the front door is unlocked or the alarm is disarmed
- id: '1001'
  alias: Security - Notify when home is unsecured
  trigger:
    platform: state
    entity_id: group.home_members
    from: 'home'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: lock.hallway_front_door_lock
          state: 'unlocked'
        - condition: state
          entity_id: alarm_control_panel.verisure_alarm
          state: 'disarmed'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Home is left unsecured! The front door is {{ states("lock.hallway_front_door_lock") }} and the alarm is {{ states("alarm_control_panel.verisure_alarm") }}!'
      data:
        channel: Security
        actions:
          - action: lock_hallway_front_door_lock
            title: 'Lock Front Door'

# Notify when entrance doorbell is ringed
- id: '1002'
  alias: Security - Notify on entrance doorbell
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_entrance_doorbell
    to: 'on'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Someone is at the front door!'
      data:
        channel: Security
        actions:
          - action: unlock_hallway_front_door_lock
            title: 'Unlock Front Door'