# Send a notification when the dishwasher is done
- alias: Appliance - Notify when dishwasher is done
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_dishwasher_state
    to: 'off'
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'The dishwasher is done.'