# Send a notification when the dishwasher is done
- alias: Appliance - Notify when dishwasher is done
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_dishwasher_state
    from: 'on'
    to: 'off'
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'The dishwasher is done.'
      data:
        channel: Appliance

# Notify when the freezer temperature is too high
- alias: Appliance - Notify on high freezer temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_freezer_temperature
    above: -10
    for:
      minutes: 20
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Freezer temperature is too high!'
      data:
        channel: Appliance

# Notify when the fridge temperature is too high
- alias: Appliance - Notify on high fridge temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_fridge_temperature
    above: 15
    for:
      minutes: 10
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Fridge temperature is too high!'
      data:
        channel: Appliance