# Start the heat when cold inside and outside
- alias: Climate - Start heating when cold
  trigger:
    platform: numeric_state
    entity_id: sensor.downstairs_average_temperature
    below: 21.5
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    below: 17
  action:
    service: climate.set_temperature
    target:
      entity_id: climate.living_room_hvac
    data:
      temperature: 20
      hvac_mode: heat

# Start the AC when warm inside and outside
- alias: Climate - Start cooling when warm
  trigger:
    platform: numeric_state
    entity_id: sensor.downstairs_average_temperature
    above: 22.5
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    above: 17
  action:
    service: climate.set_temperature
    target:
      entity_id: climate.living_room_hvac
    data:
      temperature: 23
      hvac_mode: cool

# Turn off the heat when warm inside or outside, and the heat is on
- alias: Climate - Stop heating when warm
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_average_temperature
      above: 22.5
      for:
        minutes: 30
    - platform: numeric_state
      entity_id: sensor.outdoor_temperature
      above: 17
      for:
        minutes: 30
  condition:
    condition: state
    entity_id: climate.living_room_hvac
    state: heat
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_room_hvac

# Turn off the AC when cold inside or outside, and the AC is on
- alias: Climate - Stop cooling when cold
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_average_temperature
      below: 21.5
      for:
        minutes: 30
    - platform: numeric_state
      entity_id: sensor.outdoor_temperature
      below: 17
      for:
        minutes: 30
  condition:
    condition: state
    entity_id: climate.living_room_hvac
    state: cool
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_room_hvac

# Turn off the HVAC when the TV is off, it's evening, and all downstairs lights are turned off
- alias: Climate - Turn off HVAC when going to sleep
  trigger:
    platform: state
    entity_id: group.indoor_lights
    to: 'off'
  condition:
    condition: time
    after: '21:30'
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_room_hvac