# Start the heat when cold inside and outside
- alias: Climate - Start heating when cold
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_temperature
    below: 21
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    below: 17
  action:
    service: climate.set_temperature
    target:
      entity_id: climate.living_room_hvac
    data:
      temperature: 23
      hvac_mode: heat

# Start the AC when warm inside and outside
- alias: Climate - Start cooling when warm
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_temperature
    above: 23
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    above: 17
  action:
    service: climate.set_temperature
    target:
      entity_id: climate.living_room_hvac
    data:
      temperature: 23
      hvac_mode: cool

# Turn off the heat when warm inside and cold outside
- alias: Climate - Stop heating when warm
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_temperature
    above: 23
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    below: 17
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_room_hvac

# Turn off the AC when cold inside and warm outside
- alias: Climate - Stop cooling when cold
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_temperature
    below: 21
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    above: 17
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_room_hvac