# Start the heat when cold inside and outside
- alias: Climate - Start heating when cold
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_average_temperature
      below: 21.5
      for:
        minutes: 5
    - platform: state
      entity_id: input_number.living_room_hvac_target
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    below: 17
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.living_room_hvac
    - delay:
        seconds: 5
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.living_room_hvac
      data:
        hvac_mode: heat
    - delay:
        seconds: 5
    - service: climate.set_temperature
      target:
        entity_id: climate.living_room_hvac
      data:
        temperature: '{{ states("input_number.living_room_hvac_target") }}'
    - delay:
        seconds: 5
    - service: climate.set_fan_mode
      target:
        entity_id: climate.living_room_hvac
      data:
        fan_mode: low

# Start the AC when warm inside and outside
- alias: Climate - Start cooling when warm
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_average_temperature
      above: 22.5
      for:
        minutes: 5
    - platform: state
      entity_id: input_number.living_room_hvac_target
  condition:
    condition: numeric_state
    entity_id: sensor.outdoor_temperature
    above: 17
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.living_room_hvac
    - delay:
        seconds: 5
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.living_room_hvac
      data:
        hvac_mode: cool
    - delay:
        seconds: 5
    - service: climate.set_temperature
      target:
        entity_id: climate.living_room_hvac
      data:
        temperature: '{{ states("input_number.living_room_hvac_target") }}'
    - delay:
        seconds: 5
    - service: climate.set_fan_mode
      target:
        entity_id: climate.living_room_hvac
      data:
        fan_mode: low

# Turn off the heat when warm inside or outside, and the heat is on
- alias: Climate - Stop heating when warm
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_average_temperature
      above: 22.5
      for:
        minutes: 30
    - platform: numeric_state
      entity_id: sensor.outdoor_temperature
      above: 17
      for:
        minutes: 30
  condition:
    condition: state
    entity_id: climate.living_room_hvac
    state: heat
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_room_hvac

# Turn off the AC when cold inside or outside, and the AC is on
- alias: Climate - Stop cooling when cold
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_average_temperature
      below: 21.5
      for:
        minutes: 30
    - platform: numeric_state
      entity_id: sensor.outdoor_temperature
      below: 17
      for:
        minutes: 30
  condition:
    condition: state
    entity_id: climate.living_room_hvac
    state: cool
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_room_hvac