# Turn on outdoor lights at sunset
- alias: Lighting - Turn on outdoor lights at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_comfort_lights

# Turn on indoor lights when living room becomes dark and someone is home
- alias: Lighting - Turn on indoor lights when dark and somone is home
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 10
    for:
      seconds: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.home_members
        state: 'home'
      - condition: state
        entity_id: switch.guest_mode
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_comfort_lights

# Turn on indoor lights when living room becomes dark
- alias: Lighting - Turn on indoor lights when dark
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 10
    for:
      seconds: 5
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_window_lights

# Turn off outdoor lights at sunrise
- alias: Lighting - Turn off outdoor lights at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_comfort_lights

# Turn off indoor lights when living room is bright
- alias: Lighting - Turn off indoor lights when bright
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    above: 25
    for:
      seconds: 5
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.indoor_comfort_lights
      - group.indoor_window_lights

# Turn on lights when the computer is turning on
- alias: Lighting - Turn on lights when computer start
  trigger:
    platform: state
    entity_id: group.lucas_pc
    to: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.upstairs_desk_light_computer_on

# Turn off lights when the computer is turning off
- alias: Lighting - Turn off lights when computer stop
  trigger:
    platform: state
    entity_id: group.lucas_pc
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: light.upstairs_desk_light