# Turn on outdoor lights at sunset
- alias: Lighting - Turn on outdoor lights at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_comfort_lights

# Turn on comfort lights when living room becomes dark and someone is home
- alias: Lighting - Turn on comfort lights when dark
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 6
    for:
      seconds: 60
  condition:
    - condition: sun
      after: sunrise
      before: sunset
    - condition: state
      entity_id: alarm_control_panel.snyggatorpsvagen_alarm
      state: disarmed
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.downstairs_comfort_lights
      #- group.upstairs_comfort_lights

# Turn on Lovelia's comfort lights when living room becomes dark, someone is home, and Lovelia is not sleeping
- alias: Lighting - Turn on Lovelias comfort lights when dark
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 6
    for:
      seconds: 60
  condition:
    - condition: sun
      after: sunrise
      before: sunset
    - condition: time
      before: '19:00:00'
    - condition: state
      entity_id: alarm_control_panel.snyggatorpsvagen_alarm
      state: disarmed
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: group.lovelias_room_comfort_lights

# Turn on bedroom comfort lights when living room becomes dark and someone is home
- alias: Lighting - Turn on bedroom comfort lights when dark
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 6
    for:
      seconds: 60
  condition:
    - condition: sun
      after: sunrise
      before: sunset
    - condition: state
      entity_id: alarm_control_panel.snyggatorpsvagen_alarm
      state: disarmed
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: group.bedroom_comfort_lights

# Turn on window lights when living room becomes dark
- alias: Lighting - Turn on window lights when dark
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 6
    for:
      seconds: 60
  condition:
    - condition: sun
      after: sunrise
      before: sunset
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.downstairs_window_lights
      - group.upstairs_window_lights

# Turn on Lovelia's window lights when living room becomes dark and Lovelia is not sleeping
#- alias: Lighting - Turn on Lovelias window lights when dark
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.living_room_light_level
#    below: 6
#    for:
#      seconds: 60
#  condition:
#    - condition: sun
#      after: sunrise
#      before: sunset
#    - condition: time
#      before: '19:00:00'
#    - condition: state
#      entity_id: input_boolean.night_mode
#      state: 'off'
#  action:
#    service: homeassistant.turn_on
#    entity_id: group.lovelias_room_window_lights

# Turn on bedroom window lights when living room becomes dark
#- alias: Lighting - Turn on bedroom window lights when dark
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.living_room_light_level
#    below: 6
#    for:
#      seconds: 60
#  condition:
#    - condition: sun
#      after: sunrise
#      before: sunset
#    - condition: state
#      entity_id: input_boolean.night_mode
#      state: 'off'
#  action:
#    service: homeassistant.turn_on
#    entity_id: group.bedroom_window_lights

# Turn off outdoor lights at sunrise
- alias: Lighting - Turn off outdoor lights at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_comfort_lights

# Turn off indoor lights when living room is bright
- alias: Lighting - Turn off indoor lights when bright
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    above: 9
    for:
      minutes: 5
  condition:
    condition: sun
    after: sunrise
    before: sunset
  action:
    service: homeassistant.turn_off
    entity_id: group.indoor_lights