# Turn on outdoor lights at sunset
- alias: Lighting - Turn on outdoor lights at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_comfort_lights

# Turn on indoor lights when living room becomes dark and someone is home
- alias: Lighting - Turn on indoor lights when dark and somone is home
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 10
    for:
      seconds: 5
  condition:
    condition: and
    conditions:
      - condition: time
        after: "12:00:00"
      - condition: sun
        before: sunset
      - condition: or
        conditions:
          - condition: state
            entity_id: group.home_members
            state: 'home'
          - condition: state
            entity_id: switch.guest_mode
            state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_comfort_lights

# Turn on indoor lights when living room becomes dark
- alias: Lighting - Turn on indoor lights when dark
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 7
    for:
      seconds: 5
  condition:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_window_lights

# Turn off outdoor lights at sunrise
- alias: Lighting - Turn off outdoor lights at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.outdoor_comfort_lights

# Turn off indoor lights when living room is bright
- alias: Lighting - Turn off indoor lights when bright
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    above: 9
    for:
      seconds: 5
  condition:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.indoor_lights
      - light.bedroom_night_light