# Start Spotify and play a default playlist when Living Room Harmony Hub starts Spotify
- alias: "Media - Living Room Harmony Spotify"
  trigger:
    platform: state
    entity_id: sensor.living_room_harmony_hub
    to: 'Spotify'
  action:
    - delay:
        seconds: 12
    - service: androidtv.adb_command
      data:
        entity_id: media_player.living_room_shield
        command: 'am start -a android.intent.action.VIEW -d -n com.spotify.tv.android/.SpotifyTVActivity'
    - delay:
        seconds: 10
    - service: media_player.select_source
      entity_id: media_player.spotify_lucas_hokerberg
      data:
        source: 'Living Room Shield'
    - service: media_player.play_media
      entity_id: media_player.spotify_lucas_hokerberg
      data:
        media_content_id: 'spotify:user:spotify:playlist:37i9dQZEVXcH5UOFYpBVWG'
        media_content_type: playlist

# Turn off lights and start Plex when Living Room Harmony Hub starts Movie Mode
- alias: "Media - Living Room Harmony Movie Mode"
  trigger:
    platform: state
    entity_id: sensor.living_room_harmony_hub
    to: 'Movie Mode'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - automation.lighting_turn_on_indoor_lights_when_dark_and_somone_is_home
        - automation.lighting_turn_on_indoor_lights_when_dark
        - group.downstairs_lights
    - delay:
        seconds: 12
    - service: scene.turn_on
      data:
        entity_id: scene.living_room_hue_switch_plex
        transition: 2
    - service: androidtv.adb_command
      data:
        entity_id: media_player.living_room_shield
        command: 'am start -a android.intent.action.MAIN -c android.intent.category.LEANBACK_LAUNCHER -n com.plexapp.android/com.plexapp.plex.activities.SplashActivity'

# Turn off lights when Plex is resuming or playing and Movie Mode is active
- alias: Media - Turn off lights when Plex plays
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.living_room_shield
    to: 'playing'
  condition:
    condition: state
    entity_id: sensor.living_room_harmony_hub
    state: 'Movie Mode'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.living_room_sideboard_light
        - group.living_room_floor_light
      transition: 2

# Turn on lights when Plex is pausing or stoping and Movie Mode is active
- alias: Media - Turn on lights when Plex stops
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.living_room_shield
    to: 'idle'
  condition:
    condition: state
    entity_id: sensor.living_room_harmony_hub
    state: 'Movie Mode'
  action:
    service: scene.turn_on
    data:
      entity_id: scene.living_room_hue_switch_plex
      transition: 2

# Turn on lights when Living Room Harmony Hub stops Movie Mode
- alias: Media - Turn on lights when Living Room Harmony exit Movie Mode
  trigger:
    platform: state
    entity_id: sensor.living_room_harmony_hub
    from: 'Movie Mode'
  action:
    service: homeassistant.turn_on
    data:
      entity_id:
        - scene.living_room_hue_switch_normal
        - group.downstairs_lights
        - automation.lighting_turn_on_indoor_lights_when_dark_and_somone_is_home
        - automation.lighting_turn_on_indoor_lights_when_dark

# Turn on lights when the computer is turning on
- alias: Media - Turn on lights when computer start
  trigger:
    platform: state
    entity_id: device_tracker.lucas_pc
    to: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.upstairs_desk_light_computer

# Turn off lights when the computer is turning off
- alias: Media - Turn off lights when computer stop
  trigger:
    platform: state
    entity_id: device_tracker.lucas_pc
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: light.upstairs_desk_light