# Turn on lights when motion upstairs is detected and it's dark
- alias: Motion - Turn on lights on upstairs motion
  trigger:
    platform: state
    entity_id: binary_sensor.upstairs_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: light.upstairs_desk_light
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.upstairs_light_level
      below: 5
  action:
    service: scene.turn_on
    entity_id: scene.upstairs_desk_light_night

# Turn off lights when no upstairs motion is detected and the computer is off
- alias: Motion - Turn off lights on no upstairs motion
  trigger:
    platform: state
    entity_id: binary_sensor.upstairs_motion
    to: 'off'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: group.lucas_pc
    state: 'not_home'
  action:
    service: light.turn_off
    data:
      entity_id: light.upstairs_desk_light
      transition: 2

# Turn on bedroom wardrobe light when door is opened
- alias: Presence - Turn on bedroom wardrobe light
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_wardrobe_door_sensor
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_wardrobe_light
      brightness: 104
      transition: 3

# Turn off bedroom wardrobe light when door is closed
- alias: Presence - Turn off bedroom wardrobe light
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_wardrobe_door_sensor
    to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom_wardrobe_light
      transition: 3