# Turn on lights when motion in living room is detected, it's dark and quiet, night mode is on, and guest mode is off
- alias: Motion - Turn on lights on living room motion
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: group.downstairs_comfort_lights
      state: 'off'
    - condition: state
      entity_id: remote.living_room_harmony_hub
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.living_room_light_level
      below: 5
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.living_room_floor_light_1
    - delay:
      seconds: 30
    - service: light.turn_off
      entity_id: light.living_room_floor_light_1

# Turn on lights when motion upstairs is detected, it's dark, and night mode is on
- alias: Motion - Turn on lights on upstairs motion
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.upstairs_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: light.upstairs_window_light
      state: 'off'
    - condition: state
      entity_id: device_tracker.lucas_pc
      state: 'not_home'
    - condition: numeric_state
      entity_id: sensor.upstairs_light_level
      below: 5
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.upstairs_desk_light_night
    - delay:
      seconds: 30
    - service: light.turn_off
      entity_id: light.upstairs_desk_light