# Send a notification when Lucas is arriving at work
- alias: Presence - Notify when Lucas arrives at work
  trigger:
    platform: state
    entity_id: person.lucas_hokerberg
    to: zone.lucas_hokerberg_work
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Lucas arrived at work.'
      data:
        channel: Presence

# Send a notification when Victoria is arriving at work
- alias: Presence - Notify when Victoria arrives at work
  trigger:
    platform: state
    entity_id: person.victoria_hjerter
    to: zone.victoria_hjerter_work
    for:
      minutes: 1
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Victoria arrived at work.'
      data:
        channel: Presence

# Send a notification when Lucas is leaving work
- alias: Presence - Notify when Lucas leaves work
  trigger:
    platform: state
    entity_id: person.lucas_hokerberg
    from: zone.lucas_hokerberg_work
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Lucas left work.'
      data:
        channel: Presence

# Send a notification when Victoria is leaving work
- alias: Presence - Notify when Victoria leaves work
  trigger:
    platform: state
    entity_id: person.victoria_hjerter
    from: zone.victoria_hjerter_work
    for:
      minutes: 1
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Victoria left work.'
      data:
        channel: Presence

# Turn on lights when living room is dark and someone comes home
- alias: Presence - Turn on indoor lights when someone comes home 1
  trigger:
    platform: state
    entity_id: alarm_control_panel.snyggatorpsvagen_alarm
    from: armed_away
    to: disarmed
  condition:
    condition: numeric_state
    entity_id: sensor.living_room_light_level
    below: 8
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_lights

- alias: Presence - Turn on indoor lights when someone comes home 2
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_front_door_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.snyggatorpsvagen_alarm
      state: armed_away
    - condition: numeric_state
      entity_id: sensor.living_room_light_level
      below: 8
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_lights

# Turn on the heat if cold inside and outside, and someone comes home
- alias: Presence - Turn on heat when cold and someone comes home
  trigger:
    platform: state
    entity_id: alarm_control_panel.snyggatorpsvagen_alarm
    from: armed_away
    to: disarmed
  condition:
    - condition: numeric_state
      entity_id: sensor.outdoor_temperature
      below: 17
    - condition: numeric_state
      entity_id: sensor.downstairs_average_temperature
      below: 21.5
    - condition: state
      entity_id: climate.living_room_hvac
      state: 'off'
  action:
    service: automation.trigger
    entity_id: automation.climate_start_cooling_when_warm

# Turn on the AC if warm inside and outside, and someone comes home
- alias: Presence - Turn on AC when warm and someone comes home
  trigger:
    platform: state
    entity_id: alarm_control_panel.snyggatorpsvagen_alarm
    from: armed_away
    to: disarmed
  condition:
    - condition: numeric_state
      entity_id: sensor.outdoor_temperature
      above: 17
    - condition: numeric_state
      entity_id: sensor.downstairs_average_temperature
      above: 22.5
    - condition: state
      entity_id: climate.living_room_hvac
      state: 'off'
  action:
    service: automation.trigger
    entity_id: automation.climate_start_cooling_when_warm

# Turn off lights and TV when the alarm is armed away
- alias: Presence - Turn off lights and TV when alarm is armed away
  trigger:
    platform: state
    entity_id: alarm_control_panel.snyggatorpsvagen_alarm
    to: armed_away
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.indoor_comfort_lights
      - remote.living_room_harmony_hub