# Send a notification when someone is coming home
- alias: Presence - Notify when someone comes home
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg,person.victoria_hjerter
    zone: zone.home
    event: enter
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: '{{ trigger.to_state.attributes.friendly_name }} just came home.'
      data:
        channel: Presence

# Send a nofitication when someone is leaving home
- alias: Presence - Notify when someone leaves home
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg,person.victoria_hjerter
    zone: zone.home
    event: leave
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: '{{ trigger.to_state.attributes.friendly_name }} just left the home.'
      data:
        channel: Presence

# Send a notification when Lucas is arriving at work
- alias: Presence - Notify when Lucas arrives at work
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg
    zone: zone.lucas_hokerberg_work
    event: enter
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Lucas Hökerberg just arrived at work.'
      data:
        channel: Presence

# Send a notification when Victoria is arriving at work
- alias: Presence - Notify when Victoria arrives at work
  trigger:
    platform: zone
    entity_id: person.victoria_hjerter
    zone: zone.victoria_hjerter_work
    event: enter
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Victoria Hjerter just arrived at work.'
      data:
        channel: Presence

# Send a notification when Lucas is leaving work
- alias: Presence - Notify when Lucas leaves work
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg
    zone: zone.lucas_hokerberg_work
    event: leave
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Lucas Hökerberg just left work.'
      data:
        channel: Presence

# Send a notification when Victoria is leaving work
- alias: Presence - Notify when Victoria leaves work
  trigger:
    platform: zone
    entity_id: person.victoria_hjerter
    zone: zone.victoria_hjerter_work
    event: leave
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Victoria Hjerter just left work.'
      data:
        channel: Presence

# Turn on lights when living room is dark and someone comes home
- alias: Presence - Turn on indoor lights when someone comes home 1
  trigger:
    platform: state
    entity_id: group.home_members
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.living_room_light_level
    below: 10
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.indoor_comfort_lights
      - group.indoor_window_lights

- alias: Presence - Turn on indoor lights when someone comes home 2
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_front_door_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.home_members
        state: 'not_home'
      - condition: numeric_state
        entity_id: sensor.living_room_light_level
        below: 10
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.indoor_comfort_lights
      - group.indoor_window_lights

# Turn off lights and TV when everyone leaves home
- alias: Presence - Turn off lights and TV when everyone leaves home
  trigger:
    platform: state
    entity_id: group.home_members
    from: 'home'
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.indoor_comfort_lights
      - remote.living_room_harmony_hub