# Send a notification when someone is coming home
- alias: Presence - Notify when someone comes home
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg,person.victoria_hjerter
    zone: zone.home
    event: enter
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: '{{ trigger.to_state.attributes.friendly_name }} just came home.'

# Send a nofitication when someone is leaving home
- alias: Presence - Notify when someone leaves home
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg,person.victoria_hjerter
    zone: zone.home
    event: leave
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: '{{ trigger.to_state.attributes.friendly_name }} just left the home.'

# Send a notification when Lucas is arriving at work
- alias: Presence - Notify when Lucas arrives at work
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg
    zone: zone.lucas_hokerberg_work
    event: enter
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Lucas Hökerberg just arrived at work.'

# Send a notification when Victoria is arriving at work
- alias: Presence - Notify when Victoria arrives at work
  trigger:
    platform: zone
    entity_id: person.victoria_hjerter
    zone: zone.victoria_hjerter_work
    event: enter
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Victoria Hjerter just arrived at work.'

# Send a notification when Lucas is leaving work
- alias: Presence - Notify when Lucas leaves work
  trigger:
    platform: zone
    entity_id: person.lucas_hokerberg
    zone: zone.lucas_hokerberg_work
    event: leave
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Lucas Hökerberg just left work.'

# Send a notification when Victoria is leaving work
- alias: Presence - Notify when Victoria leaves work
  trigger:
    platform: zone
    entity_id: person.victoria_hjerter
    zone: zone.victoria_hjerter_work
    event: leave
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Victoria Hjerter just left work.'

# Turn on lights when living room is dark and someone comes home
- alias: Presence - Turn on indoor lights when someone comes home
  trigger:
    platform: state
    entity_id: group.home_members
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.living_room_light_level
    below: 10
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.indoor_comfort_lights
      - group.indoor_window_lights

# Turn off lights and TV when everyone leaves home
- alias: Presence - Turn off lights and TV when everyone leaves home
  trigger:
    platform: state
    entity_id: group.home_members
    from: 'home'
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.indoor_comfort_lights
      - remote.living_room_harmony_hub

# Notify when everyone leaves the home and the front door is unlocked
- alias: Presence - Notify when door is unlocked
  trigger:
    platform: state
    entity_id: group.home_members
    from: 'home'
  condition:
    condition: state
    entity_id: lock.front_door
    state: 'unlocked'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Everyone left home, but the front door is unlocked!'
      data:
        actions:
          - action: lock_front_door
            title: 'Lock Front Door'

- alias: Precense - Notify when door is unlocked - Action
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: lock_front_door
  action:
    service: lock.lock
    entity_id: lock.front_door