# Send a reminder when a garbage cans is due tomorrow
- alias: Reminder - Garbage Cans
  trigger:
    platform: state
    entity_id: sensor.garbage_can_1,sensor.garbage_can_2,sensor.garden_waste
    to: 'tomorrow'
    for:
      hours: 8
  action:
    - service: notify.home_mobile_apps
      data_template:
        title: 'HalloNET Home'
        message: 'Reminder for {{ trigger.to_state.attributes.friendly_name }}.'