# Send a reminder when garbage can 1 is emptied tomorrow
- alias: Reminder - Garbage Can 1
  trigger:
    - platform: state
      entity_id: sensor.garbage_can_1
      to: 'tomorrow'
      for:
        hours: 8
    - platform: state
      entity_id: sensor.garbage_can_1
      to: 'tomorrow'
      for:
        hours: 20
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Garbage can 1 is emptied tomorrow.'
      data:
        channel: Reminder

# Send a reminder when garbage can 2 is emptied tomorrow
- alias: Reminder - Garbage Can 2
  trigger:
    - platform: state
      entity_id: sensor.garbage_can_2
      to: 'tomorrow'
      for:
        hours: 8
    - platform: state
      entity_id: sensor.garbage_can_2
      to: 'tomorrow'
      for:
        hours: 20
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Garbage can 2 is emptied tomorrow.'
      data:
        channel: Reminder

  # Send a reminder when garden waste is emptied tomorrow
- alias: Reminder - Garden Waste
  trigger:
    - platform: state
      entity_id: sensor.garden_waste
      to: 'tomorrow'
      for:
        hours: 8
    - platform: state
      entity_id: sensor.garden_waste
      to: 'tomorrow'
      for:
        hours: 20
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Garden waste is emptied tomorrow.'
      data:
        channel: Reminder