# Call bedtime script when the TV is off, it's evening, and all downstairs lights are turned off
- alias: Routine - Bedtime
  trigger:
    platform: state
    entity_id: group.downstairs_lights
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00'
        before: '03:00'
      - condition: state
        entity_id: remote.living_room_harmony_hub
        state: 'off'
  action:
    service: script.bedtime

# Turn off night mode one hour before an alarm is set, or in the morning
- alias: Routine - Wake up
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: template
      value_template: '{{ as_timestamp(states("sensor.lucas_hokerberg_next_alarm")) - as_timestamp(states("sensor.date_time").replace(",","")) == 3600 }}'
    - platform: template
      value_template: '{{ as_timestamp(states("sensor.victoria_hjerter_next_alarm")) - as_timestamp(states("sensor.date_time").replace(",","")) == 3600 }}'
  action:
    service: switch.turn_off
    entity_id: switch.night_mode

# Things to do when night mode switch is turned off ...
# ... and it's cold inside and outside
- alias: Routine - Wake up - Cold
  trigger:
    platform: state
    entity_id: switch.night_mode
    to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.outdoor_temperature
      below: 17
    - condition: numeric_state
      entity_id: sensor.downstairs_average_temperature
      below: 21.5
  action:
    service: automation.trigger
    entity_id: automation.climate_start_heating_when_cold

# ... and it's warm inside and outside
- alias: Routine - Wake up - Warm
  trigger:
    platform: state
    entity_id: switch.night_mode
    to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.outdoor_temperature
      above: 17
    - condition: numeric_state
      entity_id: sensor.downstairs_average_temperature
      above: 22.5
  action:
    service: automation.trigger
    entity_id: automation.climate_start_cooling_when_warm

# ... for one hour and living room is dark
- alias: Routine - Wake up - Dark
  trigger:
    platform: state
    entity_id: switch.night_mode
    to: 'off'
    for:
      minutes: 60
  condition:
    platform: numeric_state
    entity_id: sensor.living_room_light_level
    below: 10
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.upstairs_window_light
      - group.downstairs_comfort_lights