# Call bedtime script when the TV is off, it's evening, and all downstairs lights are turned off
- alias: Routine - Bedtime
  trigger:
    platform: state
    entity_id: group.downstairs_lights
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00'
        before: '03:00'
      - condition: state
        entity_id: remote.living_room_harmony_hub
        state: 'off'
  action:
    service: script.bedtime

# Turn off night mode in the morning
- alias: Routine - Turn off night mode
  trigger:
    platform: time
    at: '04:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.night_mode