# Run wake up routine when an alarm is set or in the morning, when night mode is on
- alias: Routine - Wake up
  trigger:
    - platform: template
      value_template: '{{ as_timestamp(states("sensor.lucas_hokerberg_next_alarm")) == as_timestamp(states("sensor.date_time").replace(",","")) }}'
    - platform: template
      value_template: '{{ as_timestamp(states("sensor.victoria_hjerter_next_alarm")) == as_timestamp(states("sensor.date_time").replace(",","")) }}'
    - platform: time
      at: '08:00:00'
  condition:
    condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  action:
    service: script.wake_up
    
# Wake up routine when living room is dark
- alias: Routine - Wake up and dark
  trigger:
    - platform: state
      entity_id: script.wake_up
      to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.living_room_light_level
    below: 7
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.upstairs_window_light
      - group.downstairs_window_lights

# Wake up routine when cold inside and outside
- alias: Routine - Wake up and cold
  trigger:
    platform: state
    entity_id: script.wake_up
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.outdoor_temperature
      below: 17
    - condition: numeric_state
      entity_id: sensor.downstairs_average_temperature
      below: 21.5
    - condition: state
      entity_id: climate.living_room_hvac
      state: 'off'
  action:
    service: automation.trigger
    entity_id: automation.climate_start_heating_when_cold

# Wake up routine when warm inside and outside
- alias: Routine - Wake up and warm
  trigger:
    platform: state
    entity_id: script.wake_up
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.outdoor_temperature
      above: 17
    - condition: numeric_state
      entity_id: sensor.downstairs_average_temperature
      above: 22.5
    - condition: state
      entity_id: climate.living_room_hvac
      state: 'off'
  action:
    service: automation.trigger
    entity_id: automation.climate_start_cooling_when_warm

# Run bedtime routine when the TV is off, it's evening, and all downstairs lights are turned off
- alias: Routine - Bedtime
  trigger:
    platform: state
    entity_id: group.downstairs_lights
    to: 'off'
  condition:
    - condition: time
      after: '21:00'
      before: '03:00'
    - condition: state
      entity_id: remote.living_room_harmony_hub
      state: 'off'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    service: script.bedtime