# Call bedtime script when the TV is off, it's evening, and all downstairs lights are turned off
- alias: Routine - Bedtime
  trigger:
    platform: state
    entity_id: group.downstairs_lights
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00'
        before: '03:00'
      - condition: state
        entity_id: remote.living_room_harmony_hub
        state: 'off'
  action:
    service: script.bedtime

# Turn off night mode in the morning or 1 hour prior to an alarm
- alias: Routine - Turn off night mode
  trigger:
    - platform: time
      at: '08:00:00'
    - platform: template
      value_template: '{{ as_timestamp(states("sensor.lucas_hokerberg_next_alarm")) - as_timestamp(states("sensor.date_time").replace(",","")) == 3600 }}'
  action:
    service: switch.turn_off
    entity_id: switch.night_mode