# Notify when basement water sensor is wet
- alias: Security - Notify on basement leakage
  trigger:
    platform: state
    entity_id: binary_sensor.basement_water_sensor
    to: wet
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Leakage detected in the basement!'
      data:
        channel: Security

# Notify when the freezer temperature is too high
- alias: Security - Notify on high freezer temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_freezer_temperature
    above: -10
    for:
      minutes: 10
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Freezer temperature is too high!'
      data:
        channel: Security

# Notify when the fridge temperature is too high
- alias: Security - Notify on high fridge temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_fridge_temperature
    above: 15
    for:
      minutes: 10
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Fridge temperature is too high!'
      data:
        channel: Security