# Notify when basement water sensor is wet
- alias: Security - Notify on basement leakage
  trigger:
    platform: state
    entity_id: binary_sensor.basement_water_sensor
    to: 'on'
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Leakage detected in the basement!'
      data:
        channel: Security

# Notify when kitchen water sensor is wet
- alias: Security - Notify on kitchen leakage
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_water_sensor
    to: 'on'
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Leakage detected in the kitchen!'
      data:
        channel: Security

# Notify when the freezer temperature is too high
- alias: Security - Notify on high freezer temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_freezer_temperature
    above: -10
    for:
      minutes: 20
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Freezer temperature is too high!'
      data:
        channel: Security

# Notify when the fridge temperature is too high
- alias: Security - Notify on high fridge temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_fridge_temperature
    above: 15
    for:
      minutes: 10
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Fridge temperature is too high!'
      data:
        channel: Security

# Notify when everyone leaves the home and the front door is unlocked
- alias: Security - Notify when door is unlocked
  trigger:
    platform: state
    entity_id: group.home_members
    from: 'home'
  condition:
    condition: state
    entity_id: lock.hallway_front_door_lock
    state: 'unlocked'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Everyone left home, but the front door is unlocked!'
      data:
        channel: Security
        actions:
          - action: lock_hallway_front_door_lock
            title: 'Lock Front Door'

- alias: Security - Notify when door is unlocked - Action
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: lock_hallway_front_door_lock
  action:
    service: lock.lock
    entity_id: lock.hallway_front_door_lock

# Notify when front doorbell is ringed
- alias: Security - Notify on front doorbell
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_entrance_doorbell
    from: 'on'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Someone is at the front door!'
      data:
        channel: Security
        actions:
          - action: unlock_hallway_front_door_lock
            title: 'Unlock Front Door'

- alias: Security - Notify on front doorbell - Action
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: unlock_hallway_front_door_lock
  action:
    service: lock.unlock
    entity_id: lock.hallway_front_door_lock