# Notify when basement water sensor is wet
- alias: Security - Notify on basement leakage
  trigger:
    platform: state
    entity_id: binary_sensor.basement_water_sensor
    to: 'on'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Leakage detected in the basement!'
      data:
        channel: Security

# Notify when kitchen water sensor is wet
- alias: Security - Notify on kitchen leakage
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_water_sensor
    to: 'on'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Leakage detected in the kitchen!'
      data:
        channel: Security

# Notify when everyone leaves the home and the front door is unlocked or the alarm is disarmed
- alias: Security - Notify when home is unsecured
  trigger:
    platform: state
    entity_id: group.home_members
    from: 'home'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: lock.hallway_front_door_lock
        state: 'unlocked'
      - condition: state
        entity_id: alarm_control_panel.snyggatorpsvagen_alarm
        state: 'disarmed'
  action:
    service: notify.home_mobile_apps
    data_template:
      title: 'HalloNET Home'
      message: 'Home is left unsecured! The front door is {{ states("lock.hallway_front_door_lock") }} and the alarm is {{ states("alarm_control_panel.snyggatorpsvagen_alarm") }}!'
      data:
        channel: Security
        actions:
          - action: lock_hallway_front_door_lock
            title: 'Lock Front Door'

- alias: Security - Notify when home is unsecured - Action
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: lock_hallway_front_door_lock
  action:
    service: lock.lock
    entity_id: lock.hallway_front_door_lock

# Notify when entrance doorbell is ringed, and no one is home
- alias: Security - Notify on entrance doorbell 1
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_entrance_doorbell
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.snyggatorpsvagen_alarm
    state: 'armed_away'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Someone is at the front door!'
      data:
        channel: Security

# Notify when entrance doorbell is ringed, and someone is home
- alias: Security - Notify on entrance doorbell 2
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_entrance_doorbell
    to: 'Siren active'
  condition:
    condition: state
    entity_id: group.home_members
    state: 'home'
  action:
    service: notify.home_mobile_apps
    data:
      title: 'HalloNET Home'
      message: 'Someone is at the front door!'
      data:
        channel: Security
        actions:
          - action: unlock_hallway_front_door_lock
            title: 'Unlock Front Door'

- alias: Security - Notify on entrance doorbell 2 - Action
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: unlock_hallway_front_door_lock
  action:
    service: lock.unlock
    entity_id: lock.hallway_front_door_lock

# Lock the front door when the TV is off, it's evening, and all downstairs lights are turned off
- alias: Security - Lock front door when going to sleep
  trigger:
    platform: state
    entity_id: group.indoor_lights
    to: 'off'
  condition:
    condition: time
    after: '21:30'
  action:
    service: lock.lock
    entity_id: lock.hallway_front_door_lock